apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-reverse-proxy
spec:
  image: repo.adeo.no:5443/dp-reverse-proxy:latest
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: false
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://dp-reverse-proxy.nais.preprod.local
  vault:
    enabled: false
  env:
    - name: DPI_DAGPENGER_OPPSLAG
      value: https://dagpenger-oppslag
    - name: DPI_DAGPENGER_REGEL
      value: httsp://dp-regel-api
