# Example https://github.com/nais/naiserator/blob/master/examples/nais-max.yaml
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
    app: {{app}}
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: false
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: false
  ingresses:
    - https://dp-reverse-proxy.nais.preprod.local
  env:
    - name: DPI_DP_GRAPHQL
      value: http://dp-graphql
    - name: DPI_DP_REGEL_API
      value: http://dp-regel-api